services:
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on: mongodb

  
  mongodb:
    image: mongodb:v1
    container_name: mongodb

  redis:
    image: redis:7.0
    container_name: redis

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123

  mysql:
    image: mysql:v1
    container_name: mysql

  cart:
    image: cart:v1
    container_name: cart
    depends_on: 
    - redis
    - catalogue

  user:
    image: user:v1
    container_name: user
    depends_on: 
    - mongodb
    - redis

  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on: 
    - mysql
    - cart

  payment:
    image: payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
    - cart
    - user

  frontend:
    image: frontend:v1
    container_name: frontend
    depends_on: 
    - catalogue
    - cart
    - user
    - shipping
    - payment
    ports: "80:80"  


networks:
  default:
    driver: bridge
    name: roboshop
    external: false # true if you have created network manually using docker network command

