services:
  catalogue:
    build:
      context: ./catalogue
      dockerfile: dockerfile
    image: vikas/catalogue:v1
    container_name: catalogue
    depends_on: 
    - mongodb

  
  mongodb:
    build: ./mongodb
    image: vikas/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb/data/db
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - redis/data

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
    - rabbitmq: var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123


  mysql:
    build: ./mysql
    image: vikas/mysql:v1
    container_name: mysql
  volumes:
  - mysql: var/lib/mysql

  cart:
    build:
      context: ./cart
      dockerfile: dockerfile
    image: vikas/cart:v1
    container_name: cart
    depends_on: 
    - redis
    - catalogue

  user:
    build:
      context: ./user
      dockerfile: dockerfile
    image: vikas/user:v1
    container_name: user
    depends_on: 
    - mongodb
    - redis

  shipping:
    build:
      context: ./shipping
      dockerfile: dockerfile
    image: vikas/shipping:v1
    container_name: shipping
    depends_on: 
    - mysql
    - cart

  payment:
    build:
      context: ./payment
      dockerfile: dockerfile
    image: vikas/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
    - cart
    - user

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: vikas/frontend:v1
    container_name: frontend
    ports: 
    - "80:80"  
    depends_on: 
    - catalogue
    - cart
    - user
    - shipping
    - payment 


networks:
  default:
    driver: bridge
    name: roboshop
    external: false # true if you have created network manually using docker network command

volumes:
  mongodb: # docker volume create mongodb. /var/lib/docker/volumes
  redis: 
  mysql:
  rabbitmq:

