FROM node:20.19.5-alpine3.21 AS build
WORKDIR /opt/server
COPY package.json .
COPY *.js .
RUN npm install


FROM node:20.19.5-alpine3.21 AS build
WORKDIR /opt/server
RUN addgroup -S roboshoop && adduser -S roboshop -G roboshop && \
    chwon -R roboshop:roboshoop /opt/server
EXPOSE 8080
LABEL com.project="roboshop" \
      component="user" \
      created_by="vikas"
ENV MONGO="true" \
    REDIS_URL="redis:6379" \
    MONGO_URL="mongodb://mongodb:27017/users"
COPY --from=build --chown=roboshop:roboshop /opt/server /opt/server
USER roboshop
CMD ["server.js"]
ENTRYPOINT ["node"]




# FROM node:20
# WORKDIR /opt/server
# COPY package.json .
# COPY *.js .
# RUN npm install
# ENV MONGO="true" \
#     REDIS_URL="redis:6379" \
#     MONGO_URL="mongodb://mongodb:27017/users"
# CMD ["node", "server.js"]